### ISSUE TITLE
Uso do pacote em produção

### ISSUE THREAD

**Issue by pedroalano** [artesaos/moip-subscriptions#1]
Parceiros esse pacote de vocês, é indicado para uso em produção? Se não o que vocês recomendam?

E esse outro projeto de vocês? 
https://github.com/artesaos/moip

**Comment by hernandev** [comment]
um é pra produtos e outro para assinaturas, são produtos diferentes do moip usando diferentes versões da api, se quiser usar em produção recomendo forkar o projeto pq eu só vou dar manutenção no mesmo em alguns meses

**Comment by SOSTheBlack** [comment]
para o pacote https://github.com/artesaos/moip eu dou suporte

**Comment by pedroalano** [comment]
@hernandev, obrigado pela resposta, farei o que recomendou. 

@SOSTheBlack, obrigado parceiro, está anotado, para quando eu tiver duvidas!
